server:
  port: 8081

spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka
          uri: https://github.com/GustaAltF4/microservicos-config-pruba
          search-paths: config-data
  application:
    name: config-microservice
